github: rgomezjnr
custom: ["https://www.paypal.me/rgomezjnr", PayPal]
custom: ["bitcoin:bc1qh46qmztl77d9dl8f6ezswvqdqxcaurrqegca2p", Bitcoin]
custom: ["ethereum:0xAB443e578c9eA629088e26A9009e44Ed40f68678", Ethereum]
